cards={
"The Wheel of Fortune":[
"It seems the wheel of fortune is spinning boundless opportunities your way these days. You are clearly destined for advancement, so do not hesitate to stop by your boss' office seven or eight times a day to give them an opportunity to bring up the subject. As to fortune, your income will definately increase manifold if you make the right moves. Take every opportunity to tell your superiors how your current salary is far below your expectations and quite insufficient to support your preferred lifestyle. They will feel encouraged to do better, and a raise will be imminent.", 
"Unexpected events is a keyword here. Try to do the unexpected to keep your relationships from stagnating and your friends and love interests from getting bored. If they ask for tea, get them a whisky on the rocks. If they need a hug, go for intercourse. Your relationships will flourish, and you will earn a reputation for being full of surprises.", 
"Your personality clearly needs a lot of work, so kudos for being aware of that. What you need is to seek out some outside influences to help you loosen up. Practice spontaneity and saying yes to the unexpected, like smoking weed, getting an inappropriate tattoo, or running off to marry someone you scored at the pub before either of you have had time to sober up. There are so many options!"
], 
"Justice":[
"Justice in on your side in this matter. This means you will get what you deserve. No more, no less. To advance in your career, work overtime. All night if you have to. Make sure you tell on your colleagues, if they leave before time to pick up kids or you suspect that a hangover rather than the flu is keeping them from work. Take every opportunity to correct the errors and wrongdoings of everyone in the workplace. You will be honored for your righteousness!",
"Justice is important for your relationships. Unconditional love or friendship is fine in movies and such, but in real life, what you need is balance and equality. Do not be a giver! If you get drinks for yourself and a friend, check that the number of ice cubes in your drinks is the same. If you lover gives you a massage, make sure they give you one back. If necessary, keep written account of whose turn it is.",
"The advice of this card is that you focus on virtue in everything you do. Never just do something, always keep tabs at the back of your mind whether this act will confirm your virtuousness. For example, if you meet a homeless person, give them a lecture on the importance of a nutritious diet and offer to buy them a salad, rather than just giving them money to waste on alcohol and cigarettes. Soon, you will be the most righteous version of yourself!"
]}